/// Integration test: compare Rust json_repair output against Python fixtures.
///
/// The fixtures are generated by `gen_fixtures.py` and stored as
/// `tests/fixtures.json`. Each fixture has an `input` string and an
/// `output` JSON value (or null). We assert that `parse_llm_json` returns
/// the same `serde_json::Value`.
use pra_cli_rs::json_repair::parse_llm_json;
use serde::Deserialize;
use serde_json::Value;

#[derive(Deserialize)]
struct Fixture {
    #[allow(dead_code)]
    name: String,
    input: String,
    output: Option<Value>,
}

fn load_fixtures() -> Vec<Fixture> {
    let json_str = include_str!("fixtures.json");
    serde_json::from_str(json_str).expect("failed to parse fixtures.json")
}

#[test]
fn all_fixtures_match_python_output() {
    let fixtures = load_fixtures();
    assert!(!fixtures.is_empty(), "fixtures should not be empty");

    for f in &fixtures {
        let rust_output = parse_llm_json(&f.input);
        assert_eq!(
            rust_output, f.output,
            "Mismatch for fixture '{}' (input: {:?})",
            f.name, f.input
        );
    }
}

#[test]
fn fixture_count_is_reasonable() {
    let fixtures = load_fixtures();
    // We expect at least the 14 generated fixtures
    assert!(fixtures.len() >= 14);
}
