/// Integration test: compare Rust txt_writer output against Python fixtures.
///
/// The fixtures are generated by `gen_txt_fixtures.py` and stored as
/// `tests/txt_fixtures.json`. Each fixture has an `input` markdown and an
/// `output` plain-text string. We assert that `convert_md_to_txt` returns
/// the exact same string (including newlines, spacing, and heading decorations).
use pra_cli_rs::txt_writer::convert_md_to_txt;
use serde::Deserialize;

#[derive(Deserialize)]
struct TxtFixture {
    #[allow(dead_code)]
    name: String,
    input: String,
    lang: String,
    output: String,
}

fn load_txt_fixtures() -> Vec<TxtFixture> {
    let json_str = include_str!("txt_fixtures.json");
    serde_json::from_str(json_str).expect("failed to parse txt_fixtures.json")
}

#[test]
fn all_txt_fixtures_match_python_output() {
    let fixtures = load_txt_fixtures();
    assert!(!fixtures.is_empty(), "txt fixtures should not be empty");

    for f in &fixtures {
        let rust_output = convert_md_to_txt(&f.input, &f.lang);
        assert_eq!(
            rust_output, f.output,
            "Mismatch for txt fixture '{}'\n--- Rust output:\n{}\n--- Python output:\n{}",
            f.name, rust_output, f.output
        );
    }
}

#[test]
fn txt_fixture_count_is_reasonable() {
    let fixtures = load_txt_fixtures();
    assert!(fixtures.len() >= 14);
}
